Update pylint.yml

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -19,12 +19,20 @@ jobs:
         python -m pip install --upgrade pip
         pip install pylint
     - name: Analysing the code with pylint
-      run: |
-        # Run pylint with exit-zero to prevent failure
+       run: |
+        # Run pylint with exit-zero to prevent failing the workflow
         result=$(pylint --disable=E0401,W0611,W1309,C0103,C0301,E0611 --exit-zero $(git ls-files 'pipeline/*.py'))
         
-        # Extract the score from pylint output
+        # Show the Pylint result (warnings, errors, and score) in the logs
+        echo "$result"
+        
+        # Extract the Pylint score
         score=$(echo "$result" | grep -oP 'Your code has been rated at \K[0-9]+')
         
         # Output the score for visibility
         echo "Pylint score: $score"
+        
+        # Fail the job if the score is below 7
+        if [ "$score" -lt 7 ]; then
+          echo "Pylint score is below threshold!" && exit 1
+        fi
